Get all tasks handler
gumrf/borda pull request #16
Opened 2022-03-26 04:55 UTC by rmnvlv

Divided into user and admin task-handler.

2022-03-26 06:34 UTC, 2thousandmax commented on internal/api/handler.go
> +	h.initAdminRoutes(admin)
В initAdminRoutes нужно передавать v1, а группу admin уже внутри функции создавать.

2022-03-26 06:36 UTC, 2thousandmax commented on internal/api/task_handler.go
> +
Лишний пробел

2022-03-26 06:39 UTC, 2thousandmax commented on internal/api/task_handler.go
>  	err := ctx.BodyParser(&filter)
TaskFilter не нужен для этого GET запроса. Этот роут возвращает все таски которые доступны пользователю без разбора. Но для запроса к базе нужно добавить фильтр на то что таск активный

2022-03-26 06:41 UTC, 2thousandmax commented on internal/api/task_handler.go
>  	}
TaskFilter не нужен для этого GET запроса. Этот роут возвращает все таски которые доступны пользователю без разбора. Но для запроса к базе нужно добавить фильтр на то, что таск активный

2022-03-26 06:42 UTC, 2thousandmax commented on internal/api/task_handler.go
> +	tasks, err = h.UserService.ShowAllTasks(filter, id)
Переименуй ShowAllTask в GetAllTasks

2022-03-26 06:43 UTC, 2thousandmax commented on internal/api/task_handler.go
> +		Response []domain.TaskUserResponse
Переименуй Response в Tasks и добавь json тэг

2022-03-26 06:45 UTC, 2thousandmax commented on internal/api/task_handler.go
> +	var tasks []domain.TaskUserResponse
Почему TaskUserResponse без указателя?

2022-03-26 06:55 UTC, 2thousandmax commented on internal/domain/task.go
> +}
Мы договаривались о том, что в Submissions будет поле Username, а не UserId и что будет поле isCorrect. Где это?

2022-03-26 06:56 UTC, 2thousandmax commented on internal/domain/task.go
> +	UserTaskSubmissions []UserTaskSubmission
Лучше просто назвать Submissions и добавить json тэг

2022-03-26 06:57 UTC, 2thousandmax commented on internal/domain/task.go
> +type UserTaskSubmission struct {
Переименуй в TaskSubmissionResponse

2022-03-26 06:59 UTC, 2thousandmax commented on internal/domain/task.go
> +	Hint                string `json:"hint"`
Подсказки может не быть, добавь json тэг omitempty

2022-03-26 07:02 UTC, 2thousandmax commented on internal/repository/repository.go
> +	GetTeamByUserId(userId int) (int, error) //Временный метод
В названии функции говорится, что ты хочешь получить команду, но возвращается int. WTF???

2022-03-26 07:11 UTC, 2thousandmax commented on internal/api/admin_handler.go
> +	tasks.Get("", h.getAllTasksAdmin)
Зачем суффикс admin?

2022-03-26 07:12 UTC, 2thousandmax commented on internal/api/admin_handler.go
> +	tasks := router.Group("/tasks", h.adminPermissionRequired)
Проверку на админу лучше делать на группу admin

2022-03-26 07:13 UTC, 2thousandmax commented on internal/api/admin_handler.go
> +		Response []*domain.Task
Переименовать Response в Tasks + json тэг

2022-03-26 07:13 UTC, 2thousandmax commented on internal/api/admin_handler.go
> +	var taskData domain.TaskUpdate
Что значит taskData??? Просто update

2022-03-26 07:20 UTC, 2thousandmax commented on internal/api/admin_handler.go
> +	return ctx.JSON(fiber.Map{
Предлагаю возвращать 200 ок и пустое body

2022-03-26 07:20 UTC, 2thousandmax commented on internal/api/admin_handler.go
> +	})
Предлагаю возвращать 200 ок и пустое body

2022-03-26 07:22 UTC, 2thousandmax commented on internal/api/admin_handler.go
> +}
Можно возвращать только что созданный таск

2022-03-26 07:24 UTC, 2thousandmax commented on internal/service/user_service.go
> +	// filter.IsDisabled = false ??????????????????????//
Фильтр нужно инициализировать в внутри функции, а не передавать в качестве пораметра

2022-03-26 07:30 UTC, 2thousandmax commented on internal/service/user_service.go
> +	teamId, err = s.teamRepo.GetTeamByUserId(userId) //Надо откуда-то волшебным образом высрать TeamId
TeamId можно из структуры юзера взять

2022-03-26 07:50 UTC, 2thousandmax commented on internal/service/user_service.go
> +	}
Можно как-то поизящнее сделать?

2022-03-26 07:53 UTC, 2thousandmax requested changes
Нужно исправить

2022-03-26 12:49 UTC, rmnvlv commented on internal/repository/repository.go
> +	GetTeamByUserId(userId int) (int, error) //Временный метод
временный метод, мне нужно было как-то тестить

2022-03-26 14:31 UTC, rmnvlv commented on internal/api/admin_handler.go
> +}
Для этого надо переделать метод репозитория тасков saveTask()

2022-03-26 17:58 UTC, 2thousandmax commented on internal/repository/postgres/team_postgres.go
> +		return []domain.User{}, fmt.Errorf("team repository getMembers error: Team not found with id=%v", teamId)
Используй NewErrNotFound()

2022-03-26 18:25 UTC, 2thousandmax commented on internal/service/user_service.go
> +	filter.IsDisabled = false
Заинитить подругому

2022-03-26 18:28 UTC, 2thousandmax commented on internal/service/user_service.go
> +		allSubmissions, err := s.taskRepo.GetTaskSubmissions(task.Id, userId)
teamId

2022-03-26 18:32 UTC, 2thousandmax commented on internal/service/user_service.go
> +	userTasks := make([]domain.TaskUserResponse, 0)
userScopesTasks

2022-03-26 18:36 UTC, 2thousandmax commented on internal/service/user_service.go
> +		userSubmissions := make([]domain.TaskSubmissionResponse, 0)
submissionsResponse

2022-03-26 18:39 UTC, 2thousandmax requested changes
ИСПРАВЛЯЙ!!!!!

2022-03-27 06:28 UTC, 2thousandmax approved these changes

2022-03-27 06:29 UTC, merged